### PR TITLE
Additional chi translations

### PR DESCRIPTION
**Pull request by zryuek**

### CODE REVIEW

**Comment by artvin01** [comment]
Is this being worked on still ?

**Comment by zryuek** [comment]
I'll try to finish it in a day or two, been a bit busy lately

**Comment by zryuek** [comment]
That should be it for now, I'll ask some friends to check if I'm still missing anything.

**Comment by artvin01** [comment]
> I see some weapons arent in the translation file (e.g. Ludomania). In that case, do add them using their in-game names?
> 
> ```
> "Ludomania"
> {
>     "en"    "Ludomania"
>     "chi"    "xxx"
> }
> ```

You can add them like this, yes

**Pull request merged**
